### ISSUE TITLE
Implement the hooks

### ISSUE THREAD

**Issue by makara** [Wiredcraft/loopback-connector-ioredis#1]
I've put all the hooks that we need to implement in the lib file, as empty functions. Please implement them. Notes:
- Don't copy the redis connector, instead, see how it saves the things and do it in a same or similar way.
- Coding style should be more similar to https://github.com/Wiredcraft/loopback-connector-couchbase3 rather than the redis connector.

@xavierchow Please assign to someone (or maybe yourself).

**Comment by xavierchow** [comment]
Thanks for preparation, I discussed it with @CCharlieLi yesterday and he is working on it.(I'll follow up later)

**Comment by CCharlieLi** [comment]
Done.

**Comment by makara** [comment]
Thanks. Closing.
